(() => {
  if (window.__SCHOLARK_V24_UI__) return;
  window.__SCHOLARK_V24_UI__ = true;

  const $ = (s, r=document) => r.querySelector(s);
  const $$ = (s, r=document) => [...r.querySelectorAll(s)];
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

  const css = `
  :root{--sv24-purple:#6d5dfc;--sv24-lime:#c9ff6a;--sv24-dark:#17191f;--sv24-card:#fff;--sv24-border:rgba(23,25,31,.12)}
  #sv24-home{position:fixed;top:14px;left:14px;z-index:2147483600;border:1px solid rgba(255,255,255,.25);background:#17191f;color:#fff;border-radius:999px;padding:10px 15px;font:700 13px/1.1 Inter,system-ui,sans-serif;box-shadow:0 8px 28px rgba(0,0,0,.22);cursor:pointer;display:flex;gap:8px;align-items:center}
  #sv24-home:hover{transform:translateY(-1px)}
  #sv24-launch{position:fixed;right:18px;bottom:18px;z-index:2147483600;background:var(--sv24-lime);color:#17191f;border:0;border-radius:999px;padding:13px 18px;font:800 14px Inter,system-ui,sans-serif;box-shadow:0 14px 36px rgba(0,0,0,.24);cursor:pointer}
  #sv24-overlay{position:fixed;inset:0;z-index:2147483640;background:rgba(12,13,17,.70);backdrop-filter:blur(10px);display:none;align-items:center;justify-content:center;padding:24px}
  #sv24-overlay.open{display:flex}
  .sv24-modal{width:min(1040px,96vw);max-height:92vh;overflow:auto;background:#f7f7f4;border-radius:28px;box-shadow:0 30px 100px rgba(0,0,0,.35);color:#17191f}
  .sv24-head{display:flex;align-items:flex-start;justify-content:space-between;padding:28px 30px 16px}.sv24-head h2{font:800 32px/1.05 Inter,system-ui;margin:0}.sv24-head p{margin:8px 0 0;color:#666;max-width:680px}.sv24-x{border:0;background:#e8e8e4;width:38px;height:38px;border-radius:50%;font-size:22px;cursor:pointer}
  .sv24-modes{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;padding:8px 30px 20px}.sv24-mode{border:1px solid var(--sv24-border);background:#fff;border-radius:18px;padding:16px 10px;text-align:center;font:700 14px Inter;cursor:pointer}.sv24-mode b{display:block;font-size:23px;margin-bottom:8px}.sv24-mode.active{outline:3px solid var(--sv24-purple);background:#f0efff}
  .sv24-body{padding:0 30px 30px}.sv24-controls{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:12px}.sv24-controls select{border:1px solid var(--sv24-border);background:#fff;border-radius:999px;padding:10px 14px;font:600 13px Inter}
  #sv24-prompt{width:100%;min-height:150px;resize:vertical;box-sizing:border-box;border:1px solid var(--sv24-border);background:#fff;border-radius:20px;padding:18px;font:500 16px/1.45 Inter;outline:none}#sv24-prompt:focus{box-shadow:0 0 0 3px rgba(109,93,252,.18);border-color:#6d5dfc}
  .sv24-examples{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:14px 0}.sv24-example{border:1px solid var(--sv24-border);background:#fff;border-radius:16px;padding:14px;text-align:left;cursor:pointer;font:600 13px/1.35 Inter}.sv24-example:hover{border-color:#6d5dfc}
  .sv24-generate{width:100%;border:0;border-radius:18px;padding:15px 18px;background:#17191f;color:#fff;font:800 15px Inter;cursor:pointer}.sv24-generate span{color:var(--sv24-lime)}
  .sv24-note{font:500 12px/1.45 Inter;color:#777;margin-top:10px;text-align:center}
  #sv24-explainer{margin:30px auto 40px;max-width:1180px;padding:34px;border-radius:30px;background:linear-gradient(135deg,#17191f,#29243f);color:white;box-sizing:border-box;box-shadow:0 24px 70px rgba(0,0,0,.18)}
  #sv24-explainer .eyebrow{color:var(--sv24-lime);font:800 12px Inter;letter-spacing:.12em;text-transform:uppercase}#sv24-explainer h2{font:800 clamp(28px,4vw,48px)/1.02 Inter;margin:10px 0 12px;max-width:760px}#sv24-explainer>p{color:#d7d6dc;max-width:760px;font:500 16px/1.5 Inter}
  .sv24-demo{display:grid;grid-template-columns:1.1fr .9fr;gap:24px;margin-top:24px}.sv24-steps{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.sv24-step{background:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.10);border-radius:18px;padding:16px}.sv24-step i{display:inline-flex;width:28px;height:28px;border-radius:50%;background:var(--sv24-lime);color:#17191f;align-items:center;justify-content:center;font:900 12px Inter;font-style:normal;margin-bottom:9px}.sv24-step b{display:block;font:800 14px Inter;margin-bottom:4px}.sv24-step span{color:#c8c7ce;font:500 12px/1.4 Inter}
  .sv24-ad{background:#fff;color:#17191f;border-radius:22px;padding:18px;min-height:220px;position:relative;overflow:hidden}.sv24-ad:before{content:'';position:absolute;width:180px;height:180px;background:#c9ff6a;border-radius:50%;right:-70px;top:-80px;filter:blur(2px)}.sv24-ad-title{font:800 15px Inter;position:relative}.sv24-screen{position:relative;margin-top:16px;border:1px solid #ddd;border-radius:14px;padding:12px;background:#fafafa}.sv24-cursor{height:10px;width:74%;border-radius:8px;background:#ececec;overflow:hidden}.sv24-cursor:after{content:'';display:block;height:100%;width:35%;background:#6d5dfc;animation:sv24type 2.4s infinite ease-in-out}.sv24-artifact{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:12px}.sv24-artifact div{height:62px;border-radius:9px;background:linear-gradient(135deg,#29243f,#6d5dfc);animation:sv24pop 2.4s infinite ease-in-out}.sv24-artifact div:nth-child(2){animation-delay:.15s}.sv24-artifact div:nth-child(3){animation-delay:.3s}@keyframes sv24type{0%{width:5%}55%{width:100%}100%{width:100%}}@keyframes sv24pop{0%,30%{opacity:.15;transform:translateY(8px)}60%,100%{opacity:1;transform:none}}
  .sv24-cta{display:flex;gap:10px;margin-top:18px}.sv24-cta button{border-radius:999px;padding:11px 16px;font:800 13px Inter;cursor:pointer}.sv24-primary{background:var(--sv24-lime);border:0;color:#17191f}.sv24-secondary{background:transparent;border:1px solid rgba(255,255,255,.3);color:white}
  @media(max-width:760px){.sv24-modes{grid-template-columns:repeat(2,1fr)}.sv24-demo{grid-template-columns:1fr}.sv24-examples{grid-template-columns:1fr}.sv24-steps{grid-template-columns:1fr}.sv24-modal{border-radius:20px}.sv24-head,.sv24-body{padding-left:18px;padding-right:18px}.sv24-modes{padding-left:18px;padding-right:18px}#sv24-home{top:9px;left:9px;padding:9px 11px}#sv24-launch{right:10px;bottom:10px}}
  `;
  const style=document.createElement('style'); style.id='sv24-style'; style.textContent=css; document.head.appendChild(style);

  const home=document.createElement('button'); home.id='sv24-home'; home.innerHTML='⌂ <span>Home</span>'; home.onclick=()=>{location.href=location.origin+location.pathname;}; document.body.appendChild(home);
  const launch=document.createElement('button'); launch.id='sv24-launch'; launch.textContent='✦ SCHOLARK Studio'; document.body.appendChild(launch);

  const modes={
    presentation:{icon:'▣',label:'Presentatie',count:'10 dia’s',ratio:'16:9',examples:['Maak een 12-slide NBA GOAT debate voor klas 5 VWO met bewijs, statistieken en sterke visuals.','Maak een overtuigende pitchdeck voor een duurzame startup.','Leg fotosynthese uit in een visuele presentatie voor beginners.']},
    webpage:{icon:'▤',label:'Webpagina',count:'8 secties',ratio:'Responsive',examples:['Maak een moderne landing page voor een studentenstartup.','Bouw een portfolio-site voor een jonge designer.','Maak een informatieve schoolproject-webpagina over klimaatverandering.']},
    document:{icon:'▧',label:'Document',count:'1500 woorden',ratio:'A4',examples:['Schrijf een volledig onderzoeksverslag met inleiding, hoofdvraag, deelvragen, conclusie en bronnen.','Maak een professioneel business report met executive summary en aanbevelingen.','Schrijf een sterk essay met argumenten, tegenargumenten en bronverwijzingen.']},
    social:{icon:'▥',label:'Sociaal',count:'6 posts',ratio:'Portret',examples:['Maak een 6-slide Instagram carousel over slim studeren.','Maak een LinkedIn post + visual concept voor een nieuwe productlancering.','Maak een TikTok/IG campaign concept met hooks, captions en CTA’s.']},
    graphic:{icon:'◇',label:'Grafisch',count:'1 ontwerp',ratio:'1:1',examples:['Maak een high-impact poster voor een schoolbasketbaltoernooi.','Maak een infographic over de oorzaken en gevolgen van bodemvervuiling.','Maak een strak procesdiagram voor een onderzoeksproject.']}
  };
  let active='presentation';
  const overlay=document.createElement('div'); overlay.id='sv24-overlay';
  overlay.innerHTML=`<div class="sv24-modal"><div class="sv24-head"><div><h2>Creëer met SCHOLARK Studio</h2><p>Beschrijf het eindresultaat. SCHOLARK hoort eerst te structureren, daarna te schrijven en ontwerpen, en pas dan een complete eerste versie te tonen.</p></div><button class="sv24-x" aria-label="Sluiten">×</button></div><div class="sv24-modes"></div><div class="sv24-body"><div class="sv24-controls"><select id="sv24-count"></select><select id="sv24-style"><option>Klassiek</option><option>Modern</option><option>Editorial</option><option>Bold / high impact</option><option>Minimal</option><option>Academic</option></select><select id="sv24-ratio"></select><select id="sv24-lang"><option>Nederlands</option><option>English</option><option>Español</option><option>Français</option></select></div><textarea id="sv24-prompt" placeholder="Beschrijf wat je wilt maken…"></textarea><div class="sv24-examples"></div><button class="sv24-generate">✦ Start met <span>SCHOLARK AI</span></button><div class="sv24-note">Generator-first: eerst een complete eerste versie, daarna pas handmatig bewerken.</div></div></div>`;
  document.body.appendChild(overlay);
  const modeWrap=$('.sv24-modes',overlay), examples=$('.sv24-examples',overlay), count=$('#sv24-count',overlay), ratio=$('#sv24-ratio',overlay), prompt=$('#sv24-prompt',overlay);
  function renderModes(){modeWrap.innerHTML=Object.entries(modes).map(([k,m])=>`<button class="sv24-mode ${k===active?'active':''}" data-mode="${k}"><b>${m.icon}</b>${m.label}</button>`).join(''); $$('.sv24-mode',modeWrap).forEach(b=>b.onclick=()=>{active=b.dataset.mode;renderModes();renderMode();});}
  function renderMode(){const m=modes[active]; count.innerHTML=`<option>${m.count}</option><option>5</option><option>10</option><option>15</option><option>20</option>`;ratio.innerHTML=`<option>${m.ratio}</option><option>16:9</option><option>4:3</option><option>1:1</option><option>Portret</option>`;examples.innerHTML=m.examples.map(x=>`<button class="sv24-example">${esc(x)}</button>`).join('');$$('.sv24-example',examples).forEach(b=>b.onclick=()=>{prompt.value=b.textContent;prompt.focus();});}
  renderModes();renderMode();
  launch.onclick=()=>overlay.classList.add('open');$('.sv24-x',overlay).onclick=()=>overlay.classList.remove('open');overlay.addEventListener('click',e=>{if(e.target===overlay)overlay.classList.remove('open')});

  function clickExistingTool(words){const candidates=$$('a,button,[role="button"],nav *');for(const el of candidates){const t=(el.textContent||'').trim().toLowerCase();if(words.some(w=>t===w||t.includes(w))){el.click();return true;}}return false;}
  $('.sv24-generate',overlay).onclick=()=>{
    const value=prompt.value.trim(); if(!value){prompt.focus();return;}
    localStorage.setItem('scholark_v24_intent',JSON.stringify({mode:active,prompt:value,language:$('#sv24-lang',overlay).value,style:$('#sv24-style',overlay).value,count:count.value,ratio:ratio.value,at:Date.now()}));
    const map={presentation:['presentation','presentaties'],document:['report','reports','verslag','document'],graphic:['poster','designer','grafisch'],social:['social','sociaal'],webpage:['webpage','website','webpagina']};
    const found=clickExistingTool(map[active]||[]); overlay.classList.remove('open');
    if(!found){location.hash='studio-'+active; setTimeout(()=>openWorkspaceFallback(active,value),80);} else {setTimeout(()=>autofillIntent(),650);}
  };

  function autofillIntent(){let data;try{data=JSON.parse(localStorage.getItem('scholark_v24_intent')||'null')}catch{}if(!data)return;const inputs=$$('textarea,input[type="text"]');const target=inputs.find(x=>/topic|onderwerp|prompt|beschrijf|what/i.test((x.placeholder||'')+' '+(x.name||'')+' '+(x.getAttribute('aria-label')||'')))||inputs[0];if(target&&!target.value){target.value=data.prompt;target.dispatchEvent(new Event('input',{bubbles:true}));target.dispatchEvent(new Event('change',{bubbles:true}));}}
  function openWorkspaceFallback(mode,value){overlay.classList.add('open');active=mode;renderModes();renderMode();prompt.value=value;$('.sv24-note',overlay).textContent='Deze Studio-modus heeft nog geen gekoppelde legacy-editor. De nieuwe V24 generator-backend wordt hier rechtstreeks op aangesloten.';}

  function isHome(){const h=(location.hash||'').toLowerCase();return !h||['#home','#dashboard','#start'].includes(h);}
  function injectExplainer(){if(!isHome()||$('#sv24-explainer'))return;const host=$('main')||$('[role="main"]')||$('.main')||$('.content');if(!host)return;const section=document.createElement('section');section.id='sv24-explainer';section.innerHTML=`<div class="eyebrow">SCHOLARK AI • How it works</div><h2>Weet je niet waar je moet beginnen? SCHOLARK wel.</h2><p>Van leren tot creëren: beschrijf wat je nodig hebt en SCHOLARK zet de eerste complete versie voor je klaar. Jij controleert, verbetert en exporteert.</p><div class="sv24-demo"><div><div class="sv24-steps"><div class="sv24-step"><i>1</i><b>Kies wat je wilt maken</b><span>Presentatie, webpagina, document, social content of graphic.</span></div><div class="sv24-step"><i>2</i><b>Beschrijf je doel</b><span>Onderwerp, doelgroep, taal, stijl en gewenste lengte.</span></div><div class="sv24-step"><i>3</i><b>SCHOLARK doet het voorwerk</b><span>Structuur, inhoud, ontwerp en kwaliteitscontrole vóór je resultaat ziet.</span></div><div class="sv24-step"><i>4</i><b>Review & export</b><span>Pas alleen aan wat jij anders wilt. Geen leeg canvas als startpunt.</span></div></div><div class="sv24-cta"><button class="sv24-primary" id="sv24-ad-start">Probeer SCHOLARK Studio</button><button class="sv24-secondary" id="sv24-ad-more">Bekijk hoe het werkt</button></div></div><div class="sv24-ad"><div class="sv24-ad-title">✦ Mini AI demo — van prompt naar eindresultaat</div><div class="sv24-screen"><div class="sv24-cursor"></div><div class="sv24-artifact"><div></div><div></div><div></div></div></div><p style="font:600 12px/1.45 Inter;margin:14px 0 0;color:#666">“Maak een sterke presentatie over…” → structuur → inhoud → visuals → complete eerste versie.</p></div></div>`;
    host.insertBefore(section,host.firstChild);$('#sv24-ad-start',section).onclick=()=>overlay.classList.add('open');$('#sv24-ad-more',section).onclick=()=>overlay.classList.add('open');}
  injectExplainer();autofillIntent();
  addEventListener('hashchange',()=>{setTimeout(()=>{injectExplainer();autofillIntent()},250)});
})();
