-- SCHOLARK security foundation r217
-- Additive only: security audit events are service-role-only and never expose raw IPs or tokens.

create table if not exists public.security_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid null references auth.users(id) on delete set null,
  event_type text not null check (char_length(event_type) between 1 and 80),
  outcome text not null default 'observed' check (outcome in ('allowed','blocked','failed','observed')),
  route text null check (route is null or char_length(route) <= 180),
  risk_level text not null default 'medium' check (risk_level in ('low','medium','high','critical')),
  ip_hash text null check (ip_hash is null or char_length(ip_hash) <= 64),
  session_hash text null check (session_hash is null or char_length(session_hash) <= 64),
  release text null check (release is null or char_length(release) <= 80),
  metadata jsonb not null default '{}'::jsonb,
  constraint security_events_metadata_object check (jsonb_typeof(metadata)='object')
);

alter table public.security_events enable row level security;
revoke all on table public.security_events from anon, authenticated;
grant select, insert, update, delete on table public.security_events to service_role;
grant usage, select on sequence public.security_events_id_seq to service_role;

drop policy if exists security_events_deny_clients on public.security_events;
create policy security_events_deny_clients
  on public.security_events
  as restrictive
  for all
  to anon, authenticated
  using (false)
  with check (false);

create index if not exists security_events_created_idx on public.security_events(created_at desc);
create index if not exists security_events_user_created_idx on public.security_events(user_id, created_at desc) where user_id is not null;
create index if not exists security_events_type_created_idx on public.security_events(event_type, created_at desc);

do $$
declare
  t text;
begin
  foreach t in array array[
    'profiles','goals','planner_tasks','projects','ai_chats','ai_messages','quiz_results',
    'mastery_topics','spaced_reviews','study_ahead','documents','presentations','user_files',
    'language_learning_progress','credit_wallets','credit_purchases'
  ]
  loop
    if to_regclass('public.'||quote_ident(t)) is not null then
      execute format('drop policy if exists %I on public.%I', 'scholark_mfa_opt_in_guard', t);
      execute format(
        'create policy %I on public.%I as restrictive to authenticated using (
          not exists (
            select 1 from auth.mfa_factors mf
            where mf.user_id = (select auth.uid()) and mf.status = ''verified''
          )
          or coalesce((select auth.jwt()->>''aal''),''aal1'') = ''aal2''
        ) with check (
          not exists (
            select 1 from auth.mfa_factors mf
            where mf.user_id = (select auth.uid()) and mf.status = ''verified''
          )
          or coalesce((select auth.jwt()->>''aal''),''aal1'') = ''aal2''
        )',
        'scholark_mfa_opt_in_guard', t
      );
    end if;
  end loop;
end $$;

comment on table public.security_events is 'SCHOLARK sanitized security telemetry. Service-role-only; no raw IP addresses, passwords, auth tokens, or secrets.';
